import React from 'react'

const Home = () => {
    return (
        <div className="container" style={{border:"none"}} >  
          <p style={{color:'darkgreen', borderColor:'#12100E'}}>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Magna sit amet purus gravida quis blandit. Suspendisse ultrices gravida dictum fusce ut. Etiam sit amet nisl purus in mollis nunc sed. Rhoncus aenean vel elit scelerisque mauris pellentesque. Dolor morbi non arcu risus quis varius quam quisque id. Viverra justo nec ultrices dui sapien eget mi proin. Orci nulla pellentesque dignissim enim sit. Arcu dui vivamus arcu felis bibendum ut tristique et egestas. Integer eget aliquet nibh praesent tristique magna. Malesuada bibendum arcu vitae elementum. Auctor augue mauris augue neque gravida in fermentum et. Ultricies mi quis hendrerit dolor magna eget. Eget mi proin sed libero enim sed faucibus turpis in. Ac turpis egestas sed tempus urna et pharetra pharetra massa. Ut diam quam nulla porttitor. Adipiscing at in tellus integer feugiat scelerisque varius morbi.

Turpis massa tincidunt dui ut ornare lectus sit amet est. Vel turpis nunc eget lorem dolor sed viverra ipsum. Gravida cum sociis natoque penatibus et magnis. Scelerisque viverra mauris in aliquam. Lacus vestibulum sed arcu non odio euismod lacinia. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Sed viverra tellus in hac. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Fermentum leo vel orci porta. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. A condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Lectus mauris ultrices eros in cursus. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Cursus risus at ultrices mi. Quis lectus nulla at volutpat.

Diam ut venenatis tellus in metus. Sit amet nulla facilisi morbi tempus iaculis urna id. Arcu non sodales neque sodales ut etiam sit. Varius sit amet mattis vulputate enim nulla. Ultricies integer quis auctor elit sed vulputate mi. Donec et odio pellentesque diam volutpat commodo sed egestas. Ac tortor dignissim convallis aenean. Varius sit amet mattis vulputate enim. Libero enim sed faucibus turpis in eu mi. Lacus sed viverra tellus in hac habitasse platea dictumst. Fames ac turpis egestas maecenas pharetra convallis posuere. Orci sagittis eu volutpat odio facilisis. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo nulla. Nunc sed id semper risus in. Egestas dui id ornare arcu odio ut sem. In hendrerit gravida rutrum quisque. Lectus quam id leo in vitae turpis. Egestas maecenas pharetra convallis posuere morbi leo urna.

Ut placerat orci nulla pellentesque. Donec ac odio tempor orci dapibus. Sodales ut eu sem integer vitae justo eget magna. Malesuada fames ac turpis egestas. Sed adipiscing diam donec adipiscing tristique risus nec feugiat. Pellentesque habitant morbi tristique senectus et netus. Elementum nibh tellus molestie nunc non blandit massa enim nec. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Lectus quam id leo in vitae turpis massa sed elementum. Cursus risus at ultrices mi. At volutpat diam ut venenatis. Condimentum lacinia quis vel eros donec ac odio tempor orci. Arcu bibendum at varius vel pharetra vel turpis nunc. Quis risus sed vulputate odio. Sodales ut etiam sit amet nisl. Cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo. Amet mattis vulputate enim nulla aliquet porttitor lacus luctus.

Nibh tortor id aliquet lectus proin nibh nisl condimentum id. Facilisis leo vel fringilla est ullamcorper eget nulla. Porttitor lacus luctus accumsan tortor posuere ac. Magnis dis parturient montes nascetur ridiculus. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Pretium vulputate sapien nec sagittis aliquam. Est ullamcorper eget nulla facilisi etiam. Aliquet bibendum enim facilisis gravida neque. Sed viverra tellus in hac. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris.

Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim. Laoreet non curabitur gravida arcu. Bibendum arcu vitae elementum curabitur vitae nunc sed. Mollis aliquam ut porttitor leo a diam sollicitudin. In metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Et tortor at risus viverra adipiscing at. Senectus et netus et malesuada fames. Curabitur gravida arcu ac tortor dignissim. Mollis aliquam ut porttitor leo. Neque volutpat ac tincidunt vitae semper quis lectus. Felis donec et odio pellentesque diam volutpat commodo sed egestas. Orci eu lobortis elementum nibh tellus molestie nunc non blandit. Mi quis hendrerit dolor magna eget est lorem ipsum dolor. Ullamcorper eget nulla facilisi etiam. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Quam vulputate dignissim suspendisse in est.

Nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce ut placerat orci nulla pellentesque. Sed arcu non odio euismod lacinia at quis risus sed. Vestibulum rhoncus est pellentesque elit. Gravida cum sociis natoque penatibus et. Sit amet commodo nulla facilisi nullam vehicula ipsum. Fames ac turpis egestas sed tempus urna et. Eget velit aliquet sagittis id consectetur purus ut faucibus. Mi in nulla posuere sollicitudin aliquam. Odio facilisis mauris sit amet. Vivamus arcu felis bibendum ut. Eget gravida cum sociis natoque penatibus et magnis. Sodales ut eu sem integer vitae justo eget magna fermentum. Amet risus nullam eget felis eget nunc lobortis mattis. Fusce ut placerat orci nulla. In nisl nisi scelerisque eu ultrices vitae auctor eu augue.

Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Eget dolor morbi non arcu risus. Gravida cum sociis natoque penatibus. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. Fusce ut placerat orci nulla pellentesque. Id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Rhoncus est pellentesque elit ullamcorper dignissim. Suspendisse potenti nullam ac tortor vitae. Vel turpis nunc eget lorem dolor sed viverra ipsum. Arcu ac tortor dignissim convallis aenean et tortor at. Morbi non arcu risus quis varius quam. Amet tellus cras adipiscing enim. Sit amet nisl suscipit adipiscing. Ultrices neque ornare aenean euismod elementum nisi quis eleifend quam.

Turpis egestas maecenas pharetra convallis posuere. Sed enim ut sem viverra aliquet eget. Sed tempus urna et pharetra pharetra massa massa ultricies. Tristique et egestas quis ipsum suspendisse ultrices. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Tristique nulla aliquet enim tortor at auctor. Montes nascetur ridiculus mus mauris vitae. Consequat nisl vel pretium lectus quam id leo in. Nec sagittis aliquam malesuada bibendum arcu. Tempus iaculis urna id volutpat lacus laoreet non curabitur. Gravida cum sociis natoque penatibus et magnis dis parturient. Urna nec tincidunt praesent semper. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Fermentum dui faucibus in ornare. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Arcu felis bibendum ut tristique et. Justo laoreet sit amet cursus sit.

Proin sed libero enim sed faucibus turpis in eu. Habitant morbi tristique senectus et netus et malesuada fames. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Luctus venenatis lectus magna fringilla urna porttitor rhoncus. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. In fermentum et sollicitudin ac orci phasellus. Proin libero nunc consequat interdum varius sit amet mattis vulputate. Congue mauris rhoncus aenean vel elit scelerisque mauris. Eget aliquet nibh praesent tristique magna. Nunc sed blandit libero volutpat sed cras. Amet justo donec enim diam vulputate. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Metus vulputate eu scelerisque felis imperdiet proin. Risus viverra adipiscing at in. Interdum velit euismod in pellentesque massa placerat duis ultricies.</p>      
        </div>
    )
}

export default Home
